# Generated by Django 5.2.14 on 2026-06-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('chatbot_id', models.AutoField(primary_key=True, serialize=False, verbose_name='챗봇 식별 번호')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의 식별 번호')),
                ('meeting_users', models.ForeignKey(db_column='meeting_users_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingusers', verbose_name='회의 참여자')),
            ],
            options={
                'db_table': 'chatbot',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_history_id', models.AutoField(primary_key=True, serialize=False, verbose_name='챗봇 내역 식별 번호')),
                ('type', models.IntegerField(verbose_name='유형(1:질문, 2:답변)')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='질문/응답 일시')),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbot', verbose_name='챗봇 식별 번호')),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
    ]
