# Generated by Django 6.0.5 on 2026-06-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("meetings", "0005_alter_meeting_created_at_alter_meeting_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="chatbot_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="챗봇 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="meeting",
            field=models.ForeignKey(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
                verbose_name="회의 식별 번호",
            ),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="meeting_users",
            field=models.ForeignKey(
                db_column="meeting_users_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meetingusers",
                verbose_name="회의 참여자",
            ),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="chat",
            field=models.ForeignKey(
                db_column="chat_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.chatbot",
                verbose_name="챗봇 식별 번호",
            ),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="chat_history_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="챗봇 내역 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="질문/응답 일시"
            ),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="type",
            field=models.IntegerField(verbose_name="유형(1:질문, 2:답변)"),
        ),
    ]
