# Generated by Django 6.0.5 on 2026-06-19 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="meeting_users",
            field=models.ForeignKey(
                blank=True,
                db_column="meeting_users_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meetingusers",
                verbose_name="회의 참여자",
            ),
        ),
    ]
