# Generated by Django 4.2.7 on 2026-06-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False, verbose_name='회의 식별 번호')),
                ('title', models.CharField(max_length=90, verbose_name='회의 주제')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='회의 장소')),
                ('meeting_at', models.DateTimeField(verbose_name='회의 일시')),
                ('meeting_document', models.TextField(blank=True, null=True, verbose_name='회의록')),
                ('during_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='회의 진행 시간')),
                ('meeting_status', models.IntegerField(choices=[(0, '회의 전'), (1, '회의 진행 중'), (2, '회의 후')], default=0, verbose_name='회의 상태')),
                ('is_meeting_approve', models.BooleanField(default=False, verbose_name='회의록 승인 여부')),
                ('is_paused', models.BooleanField(default=False, verbose_name='일시 정지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('creator', models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to='users.users', verbose_name='회의 생성자')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '회의',
                'verbose_name_plural': '회의',
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='MeetingPreparation',
            fields=[
                ('preration_id', models.AutoField(primary_key=True, serialize=False, verbose_name='회의 준비 자료 식별 번호')),
                ('purpose', models.TextField(null=True, verbose_name='회의 목적')),
                ('project_status', models.TextField(null=True, verbose_name='프로젝트 현재 상태')),
                ('rule', models.TextField(null=True, verbose_name='규정')),
                ('effect', models.TextField(null=True, verbose_name='회의 종료 후 기대효과')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
            ],
            options={
                'db_table': 'meeting_preparation',
            },
        ),
        migrations.CreateModel(
            name='MeetingUsers',
            fields=[
                ('meeting_users_id', models.AutoField(primary_key=True, serialize=False, verbose_name='회의 참여자 식별 번호')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='참여자')),
            ],
            options={
                'db_table': 'meeting_users',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='녹음 원문 식별 번호')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='RecordUtterance',
            fields=[
                ('utterance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='발화 내역 식별 번호')),
                ('speaker', models.CharField(max_length=20, verbose_name='매핑전 발화자')),
                ('time', models.CharField(max_length=30, verbose_name='발화 시각')),
                ('content', models.TextField(verbose_name='발화 내용')),
                ('meeting_users', models.ForeignKey(blank=True, db_column='meeting_users_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meetingusers', verbose_name='실제 참여자')),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.record', verbose_name='녹음 원문')),
            ],
            options={
                'verbose_name': '발화 내역',
                'verbose_name_plural': '발화 내역',
                'db_table': 'record_utterance',
            },
        ),
        migrations.CreateModel(
            name='PreparationDocument',
            fields=[
                ('prepartion_document_id', models.AutoField(primary_key=True, serialize=False, verbose_name='참고 자료 식별번호')),
                ('document_id', models.IntegerField(verbose_name='내부문서 식별번호')),
                ('preparation', models.ForeignKey(db_column='preration_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingpreparation', verbose_name='회의 준비 자료 식별 번호')),
            ],
            options={
                'db_table': 'prepartion_document',
            },
        ),
        migrations.CreateModel(
            name='MeetingTask',
            fields=[
                ('meeting_task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='태스크 식별 번호')),
                ('title', models.CharField(max_length=255, verbose_name='업무 제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='업무 내용')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='업무 마감 기한')),
                ('priority', models.CharField(blank=True, choices=[('Highest', 'Highest'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Lowest', 'Lowest')], max_length=20, null=True, verbose_name='업무 우선순위')),
                ('status', models.IntegerField(choices=[(0, '미완료'), (1, '진행중'), (2, '완료')], default=0, verbose_name='업무 상태')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
                ('meeting_users', models.ForeignKey(blank=True, db_column='meeting_users_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meetingusers', verbose_name='담당자')),
            ],
            options={
                'db_table': 'meeting_task',
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendas',
            fields=[
                ('agenda_id', models.AutoField(primary_key=True, serialize=False, verbose_name='안건 식별 번호')),
                ('content', models.TextField(verbose_name='안건 내용')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의 식별 번호')),
            ],
            options={
                'db_table': 'meeting_agendas',
            },
        ),
    ]
