# Generated by Django 5.2.14 on 2026-06-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False, verbose_name='회의 식별 번호')),
                ('title', models.CharField(max_length=90, verbose_name='회의 주제')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='회의 장소')),
                ('meeting_at', models.DateTimeField(verbose_name='회의 일시')),
                ('meeting_document', models.TextField(blank=True, null=True, verbose_name='회의록')),
                ('is_meeting', models.BooleanField(default=False, verbose_name='회의 진행 여부')),
                ('status', models.CharField(choices=[('scheduled', '회의 예정'), ('in_progress', '진행 중'), ('finished', '종료')], default='scheduled', max_length=20, verbose_name='회의 상태')),
                ('minutes_status', models.CharField(blank=True, choices=[('draft', '검토 전'), ('approved', '검토 완료')], max_length=20, null=True, verbose_name='회의록 승인 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('creator', models.ForeignKey(blank=True, db_column='creator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to='users.users', verbose_name='회의 생성자')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='프로젝트')),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('meeting', models.OneToOneField(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meetings.meeting', verbose_name='회의')),
                ('record_row_text', models.TextField(blank=True, null=True, verbose_name='녹음 원본 텍스트')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendas',
            fields=[
                ('agenda_id', models.AutoField(primary_key=True, serialize=False, verbose_name='안건 식별 번호')),
                ('content', models.TextField(verbose_name='안건 내용')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의 식별 번호')),
            ],
            options={
                'db_table': 'meeting_agendas',
            },
        ),
        migrations.CreateModel(
            name='MeetingPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(verbose_name='준비 자료 내용')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
            ],
            options={
                'db_table': 'meeting_preparation',
            },
        ),
        migrations.CreateModel(
            name='MeetingUsers',
            fields=[
                ('meeting_users_id', models.AutoField(primary_key=True, serialize=False, verbose_name='회의 참여자 식별 번호')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='참여자')),
            ],
            options={
                'db_table': 'meeting_users',
            },
        ),
        migrations.CreateModel(
            name='MeetingTask',
            fields=[
                ('meeting_task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='태스크 식별 번호')),
                ('title', models.CharField(max_length=255, verbose_name='업무 제목')),
                ('content', models.TextField(blank=True, verbose_name='업무 내용')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='업무 마감 기한')),
                ('priority', models.CharField(blank=True, max_length=20, verbose_name='업무 우선순위(# High/Medium/Low/Lowest)')),
                ('status', models.IntegerField(default=0, verbose_name='업무 상태(0=미완료, 1=진행중, 2=완료)')),
                ('is_jira_synced', models.BooleanField(default=False, verbose_name='Jira 등록 여부')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
                ('meeting_users', models.ForeignKey(blank=True, db_column='meeting_users_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meetingusers', verbose_name='담당자')),
            ],
            options={
                'db_table': 'meeting_task',
            },
        ),
        migrations.CreateModel(
            name='OuterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='OCR 파일 경로')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의 식별 번호')),
            ],
            options={
                'db_table': 'outer_document',
            },
        ),
        migrations.CreateModel(
            name='SpeakerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_label', models.CharField(max_length=20, verbose_name='발화자 라벨')),
                ('meeting', models.ForeignKey(db_column='meeting_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
                ('meeting_users', models.ForeignKey(db_column='meeting_users_id', on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingusers', verbose_name='실제 참여자')),
            ],
            options={
                'db_table': 'speaker_mapping',
            },
        ),
    ]
