# Generated by Django 5.2.14 on 2026-06-07 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_users',
        ),
        migrations.RemoveField(
            model_name='meetingagendas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meetingusers',
            name='record',
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(blank=True, db_column='creator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to='users.users'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_status',
            field=models.CharField(blank=True, choices=[('draft', '초안'), ('reviewing', '검토중'), ('approved', '승인'), ('rejected', '거절')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='special_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', '회의 예정'), ('in_progress', '진행 중'), ('finished', '종료')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingagendas',
            name='agenda_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='meetingagendas',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingagendas',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingtask',
            name='is_jira_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingtask',
            name='jira_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meetingtask',
            name='owner',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='meetingtask',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtask',
            name='meeting_users',
            field=models.ForeignKey(blank=True, db_column='meeting_users_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingusers'),
        ),
        migrations.AlterField(
            model_name='meetingtask',
            name='priority',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingtask',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
