# Generated by Django 6.0.5 on 2026-06-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_remove_meeting_meeting_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_label", models.CharField(max_length=20)),
                (
                    "meeting",
                    models.ForeignKey(
                        db_column="meeting_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetings.meeting",
                    ),
                ),
                (
                    "meeting_users",
                    models.ForeignKey(
                        db_column="meeting_users_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetings.meetingusers",
                    ),
                ),
            ],
            options={
                "db_table": "speaker_mapping",
            },
        ),
    ]
