# Generated by Django 6.0.5 on 2026-06-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_speakermapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="meeting",
            field=models.OneToOneField(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
            ),
        ),
    ]
