# Generated by Django 6.0.5 on 2026-06-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_alter_record_meeting"),
        ("projects", "0002_project_context_alter_project_created_at_and_more"),
        ("users", "0004_alter_dept_dept_id_alter_dept_dept_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_column="creator_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_meetings",
                to="users.users",
                verbose_name="회의 생성자",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="end_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="회의 종료 일시"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="is_meeting",
            field=models.BooleanField(default=False, verbose_name="회의 진행 여부"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="회의 장소"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_at",
            field=models.DateTimeField(verbose_name="회의 일시"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_document",
            field=models.TextField(blank=True, null=True, verbose_name="회의록"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="회의 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="minutes_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "초안"),
                    ("before_review", "검토 전"),
                    ("reviewing", "검토중"),
                    ("approved", "승인"),
                    ("rejected", "거절"),
                    ("completed", "완료"),
                ],
                max_length=20,
                null=True,
                verbose_name="회의록 승인 상태",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="project",
            field=models.ForeignKey(
                db_column="project_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="special_note",
            field=models.TextField(blank=True, null=True, verbose_name="특이 사항"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "회의 예정"),
                    ("in_progress", "진행 중"),
                    ("finished", "종료"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="회의 상태",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="title",
            field=models.CharField(max_length=90, verbose_name="회의 주제"),
        ),
        migrations.AlterField(
            model_name="meetingagendas",
            name="agenda_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="안건 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="meetingagendas",
            name="content",
            field=models.TextField(verbose_name="안건 내용"),
        ),
        migrations.AlterField(
            model_name="meetingagendas",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="안건 확정 여부"),
        ),
        migrations.AlterField(
            model_name="meetingagendas",
            name="meeting",
            field=models.ForeignKey(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
                verbose_name="회의 식별 번호",
            ),
        ),
        migrations.AlterField(
            model_name="meetingagendas",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="안건 사유"),
        ),
        migrations.AlterField(
            model_name="meetingpreparation",
            name="document",
            field=models.TextField(verbose_name="준비 자료 내용"),
        ),
        migrations.AlterField(
            model_name="meetingpreparation",
            name="meeting",
            field=models.ForeignKey(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
                verbose_name="회의",
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="content",
            field=models.TextField(blank=True, verbose_name="업무 내용"),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="업무 마감 기한"
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="is_jira_synced",
            field=models.BooleanField(default=False, verbose_name="Jira 등록 여부"),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="jira_key",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Jira 이슈 키"
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="meeting",
            field=models.ForeignKey(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
                verbose_name="회의",
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="meeting_task_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="태스크 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="meeting_users",
            field=models.ForeignKey(
                blank=True,
                db_column="meeting_users_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meetingusers",
                verbose_name="담당자",
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="owner",
            field=models.CharField(
                blank=True, max_length=90, verbose_name="담당자 이름"
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="priority",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="업무 우선순위(High/Medium/Low/Lowest)",
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="status",
            field=models.IntegerField(
                default=0, verbose_name="업무 상태(0=미완료, 1=진행중, 2=완료)"
            ),
        ),
        migrations.AlterField(
            model_name="meetingtask",
            name="title",
            field=models.CharField(max_length=255, verbose_name="업무 제목"),
        ),
        migrations.AlterField(
            model_name="meetingusers",
            name="meeting",
            field=models.ForeignKey(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
                verbose_name="회의",
            ),
        ),
        migrations.AlterField(
            model_name="meetingusers",
            name="meeting_users_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="회의 참여자 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="meetingusers",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
                verbose_name="참여자",
            ),
        ),
        migrations.AlterField(
            model_name="outerdocument",
            name="meeting",
            field=models.ForeignKey(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
                verbose_name="회의 식별 번호",
            ),
        ),
        migrations.AlterField(
            model_name="outerdocument",
            name="path",
            field=models.TextField(verbose_name="OCR 파일 경로"),
        ),
        migrations.AlterField(
            model_name="record",
            name="meeting",
            field=models.OneToOneField(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
                verbose_name="회의",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="녹음 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_path",
            field=models.TextField(
                blank=True, null=True, verbose_name="녹음 파일 경로"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_row_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="녹음 원본 텍스트"
            ),
        ),
        migrations.AlterField(
            model_name="speakermapping",
            name="meeting",
            field=models.ForeignKey(
                db_column="meeting_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meeting",
                verbose_name="회의",
            ),
        ),
        migrations.AlterField(
            model_name="speakermapping",
            name="meeting_users",
            field=models.ForeignKey(
                db_column="meeting_users_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="meetings.meetingusers",
                verbose_name="실제 참여자",
            ),
        ),
        migrations.AlterField(
            model_name="speakermapping",
            name="speaker_label",
            field=models.CharField(max_length=20, verbose_name="발화자 라벨"),
        ),
    ]
