# Generated by Django 6.0.5 on 2026-06-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False, verbose_name='문서 식별 번호')),
                ('title', models.CharField(max_length=255, verbose_name='문서명')),
                ('path', models.CharField(max_length=500, verbose_name='문서 경로')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='프로젝트')),
                ('uploader', models.ForeignKey(db_column='uploader_id', on_delete=django.db.models.deletion.PROTECT, to='projects.projectusers', verbose_name='문서 등록자')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
