# Generated by Django 6.0.5 on 2026-06-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("projects", "0002_project_context_alter_project_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="문서 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="path",
            field=models.CharField(max_length=500, verbose_name="문서 경로"),
        ),
        migrations.AlterField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                db_column="project_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=255, verbose_name="문서명"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="업로드 일시"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploader",
            field=models.ForeignKey(
                db_column="uploader_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="projects.projectusers",
                verbose_name="문서 등록자",
            ),
        ),
    ]
