# Generated by Django 4.2.7 on 2026-06-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False, verbose_name='부서 식별 번호')),
                ('dept_name', models.CharField(max_length=20, verbose_name='부서명')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '부서',
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False, verbose_name='직급 식별 번호')),
                ('rank_name', models.CharField(max_length=20, verbose_name='직급명')),
            ],
            options={
                'verbose_name': '직급',
                'verbose_name_plural': '직급',
                'db_table': 'rank',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False, verbose_name='유저 식별 번호')),
                ('emp_no', models.CharField(max_length=20, verbose_name='사번')),
                ('email', models.EmailField(max_length=255, verbose_name='이메일')),
                ('name', models.CharField(max_length=90, verbose_name='이름')),
                ('work', models.CharField(max_length=150, verbose_name='담당 업무')),
                ('password', models.CharField(default=None, max_length=255, verbose_name='비밀번호')),
                ('account_status', models.IntegerField(default=0, verbose_name='계정 상태')),
                ('status', models.IntegerField(default=0, verbose_name='사용자 상태')),
                ('role', models.CharField(default='USER', max_length=20, verbose_name='관리자/사용자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='계정 수정 일시')),
                ('jira_account_id', models.CharField(blank=True, db_column='jira_account_Id', max_length=255, null=True, verbose_name='아이디')),
                ('jira_access_token', models.TextField(blank=True, null=True, verbose_name='Jira 액세스 토큰')),
                ('jira_refresh_token', models.TextField(blank=True, null=True, verbose_name='Jira 리프레시 토큰')),
                ('jira_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Jira 토큰 만료 일시')),
                ('jira_cloud_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jira 클라우드 ID')),
                ('jira_project_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jira 프로젝트 키')),
                ('dept', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.PROTECT, to='users.dept', verbose_name='부서')),
                ('rank', models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, to='users.rank', verbose_name='직급')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'users',
            },
        ),
    ]
