# Generated by Django 6.0.5 on 2026-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="jira_project_key",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Jira 프로젝트 키"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(
                default="abc123", max_length=255, verbose_name="비밀번호"
            ),
        ),
    ]
