# Generated by Django 6.0.5 on 2026-06-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_initial_password',
            field=models.BooleanField(default=True, verbose_name='최초 비밀번호'),
        ),
    ]
