# Generated by Django 5.2.14 on 2026-06-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': '부서', 'verbose_name_plural': '부서'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': '직급', 'verbose_name_plural': '직급'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
        migrations.AddField(
            model_name='users',
            name='jira_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='jira_cloud_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='jira_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='jira_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_id',
            field=models.CharField(blank=True, db_column='account_Id', max_length=255, null=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_status',
            field=models.IntegerField(default=0, verbose_name='계정 상태'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dept',
            field=models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.PROTECT, to='users.dept', verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='users',
            name='emp_no',
            field=models.CharField(max_length=20, verbose_name='사번'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=90, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='abc123', max_length=255, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='users',
            name='rank',
            field=models.ForeignKey(db_column='rank_id', on_delete=django.db.models.deletion.PROTECT, to='users.rank', verbose_name='직급'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='USER', max_length=20, verbose_name='관리자/사용자'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=0, verbose_name='사용자 상태'),
        ),
        migrations.AlterField(
            model_name='users',
            name='work',
            field=models.CharField(max_length=150, verbose_name='담당 업무'),
        ),
    ]
