
# Generated by Django 6.0.5 on 2026-06-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_initial_password',
        ),
    ]
