# Generated by Django 5.2.14 on 2026-06-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_dept_options_alter_rank_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jira_access_token',
            field=models.TextField(blank=True, null=True, verbose_name=' Jira API '),
        ),
        migrations.AlterField(
            model_name='users',
            name='jira_cloud_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='jira_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='access_token 재발급 필요 여부'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jira_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='만료 여부'),
        ),
    ]
