# Generated by Django 4.2.7 on 2026-06-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_initial_password'),
        ('users', '0002_users_jira_project_key_alter_users_password'),
    ]

    operations = [
    ]
