# Generated by Django 6.0.5 on 2026-06-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_jira_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dept",
            name="dept_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="부서 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="dept",
            name="dept_name",
            field=models.CharField(max_length=20, verbose_name="부서명"),
        ),
        migrations.AlterField(
            model_name="rank",
            name="rank_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="직급 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="rank_name",
            field=models.CharField(max_length=20, verbose_name="직급명"),
        ),
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="계정 생성 일시"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="jira_access_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Jira 액세스 토큰"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="jira_cloud_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Jira 클라우드 ID"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="jira_refresh_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Jira 리프레시 토큰"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="jira_token_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Jira 토큰 만료 일시"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="계정 수정 일시"),
        ),
        migrations.AlterField(
            model_name="users",
            name="users_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="유저 식별 번호"
            ),
        ),
    ]
