# Generated by Django 6.0.5 on 2026-06-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='프로젝트 식별 번호')),
                ('project_name', models.CharField(max_length=90, verbose_name='프로젝트 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='프로젝트 생성 일시')),
                ('context', models.CharField(blank=True, max_length=300, null=True, verbose_name='프로젝트 맥락 파악')),
                ('jira_project_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jira 프로젝트 키')),
                ('project_owner', models.ForeignKey(db_column='project_owner_id', on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to='users.users', verbose_name='프로젝트 생성자')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectUsers',
            fields=[
                ('project_users_id', models.AutoField(primary_key=True, serialize=False, verbose_name='프로젝트 구성원 식별 번호')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='어떤 프로젝트인지')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='프로젝트 참여자')),
            ],
            options={
                'db_table': 'project_users',
            },
        ),
    ]
