# Generated by Django 6.0.5 on 2026-06-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0004_alter_dept_dept_id_alter_dept_dept_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="context",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="프로젝트 맥락 파악"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="프로젝트 생성 일시"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="프로젝트 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=90, verbose_name="프로젝트 이름"),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_owner",
            field=models.ForeignKey(
                db_column="project_owner_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_projects",
                to="users.users",
                verbose_name="프로젝트 생성자",
            ),
        ),
        migrations.AlterField(
            model_name="projectusers",
            name="project",
            field=models.ForeignKey(
                db_column="project_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="어떤 프로젝트인지",
            ),
        ),
        migrations.AlterField(
            model_name="projectusers",
            name="project_users_id",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                verbose_name="프로젝트 구성원 식별 번호",
            ),
        ),
        migrations.AlterField(
            model_name="projectusers",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
                verbose_name="프로젝트 참여자",
            ),
        ),
    ]
