# Generated by Django 6.0.5 on 2026-06-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="context",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="프로젝트 맥락 파악"
            ),
        ),
    ]
