# Generated by Django 5.2.14 on 2026-06-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False, verbose_name='알림 식별 번호')),
                ('content', models.TextField(verbose_name='알림 내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부(0:안읽음, 1:읽음)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='알림 생성 일시')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='알림 수신자 식별 번호')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
