# Generated by Django 6.0.5 on 2026-06-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False, verbose_name='알림 식별 번호')),
                ('notification_type', models.CharField(choices=[('project_member_added', '프로젝트 팀원 추가'), ('meeting_invited', '회의 초대'), ('meeting_started', '회의 시작'), ('minutes_approved', '회의록 확정 완료'), ('task_assigned', '업무 배정')], max_length=50, verbose_name='알림 유형')),
                ('content', models.TextField(verbose_name='알림 내용')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='알림 대상 식별 번호')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부(0:안읽음, 1:읽음)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='알림 생성 일시')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='알림 수신자 식별 번호')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_715af4_idx')],
            },
        ),
    ]
