# Generated by Django 6.0.5 on 2026-06-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_created_at"),
        ("users", "0004_alter_dept_dept_id_alter_dept_dept_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.TextField(verbose_name="알림 내용"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="알림 생성 일시"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                default=False, verbose_name="읽음 여부(0:안읽음, 1:읽음)"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="알림 식별 번호"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.users",
                verbose_name="알림 수신자 식별 번호",
            ),
        ),
    ]
